### ISSUE TITLE
Add to the Catalog when we create from a Template

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#120]
Given we have create a Project from a template
When we merge the PR
And Backstage discovers the catalog entry (WIP in another ticket)
Then the project should appear as a Resource in the Catalog

--

Create **catalog-info.yaml**:

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: project
  title: Project
  description: A GCP Project with a budget and budget alerts.
  annotations:
    backstage.io/source-template: template:default/project-create
spec:
  type: project
  owner: user:current.user

```

For the owner, we can try the `ctx.user.ref` for now which _should_ look like `user:default/kendra.d`.

### Tech Notes

* Create a `catalog-info.yaml` as part of the PR template
* Configure GitHub Discover for the sci-portal and sci-portal-users repos following [the docs](https://backstage.io/docs/integrations/github/discovery)
* ⚠ The `user` is not passed to the `fetch:template`'s render method here - https://github.com/backstage/backstage/blob/v1.27.5/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/template.ts#L233-L235
